---

- name: Deploy binary tidb package
  copy: src="{{ resources_dir }}/bin/tidb-server" dest="{{ deploy_dir }}/bin/" mode=0755 backup=yes
  register: tidb_binary

- name: Backup binary file
  command: mv "{{ tidb_binary.backup_file }}" "{{ backup_dir }}"
  when: tidb_binary.changed and tidb_binary.backup_file is defined

- name: Create run script
  template:
    src: "{{ item }}_tidb_binary.sh.j2"
    dest: "{{ deploy_dir }}/scripts/{{ item }}_tidb.sh"
    mode: "0755"
    backup: yes
  with_items:
    - run
  vars:
    role_status_dir: status/{{ role_name }}
  register: tidb_script

- name: Backup script file
  command: mv "{{ tidb_script.backup_file }}" "{{ backup_dir }}"
  when: tidb_script.changed and tidb_script.backup_file is defined

- include: "{{ process_supervision }}_deployment.yml"
