---

- name: Deploy binary PD
  copy: src="{{ resources_dir }}/bin/pd-server" dest="{{ deploy_dir }}/bin/" mode=0755 backup=yes
  register: pd_binary

- name: Backup bianry file
  command: mv "{{ pd_binary.backup_file }}" "{{ backup_dir }}"
  when: pd_binary.changed and pd_binary.backup_file is defined

- name: Create startup script
  template:
    src: "{{ item }}_pd_binary.sh.j2"
    dest: "{{ deploy_dir }}/scripts/{{ item }}_pd.sh"
    mode: "0755"
    backup: yes
  with_items:
    - run
  vars:
    role_status_dir: status/{{ role_name }}

- include: "{{ process_supervision }}_deployment.yml"
