---
# handlers file for common

- name: restart ntp
  service: name=ntpd state=restarted

- name: restart sshd
  service: name=sshd state=restarted

- name: restart network
  service: name=network state=restarted
