---
# handlers file for monitor

- name: systemctl daemon-reload
  systemd: daemon_reload=yes

- name: restart alertmanager
  service: name=alertmanager state=restarted

- name: restart athene
  service: name=athene state=restarted

- name: restart prometheus
  service: name=prometheus state=restarted
