---

# Add root public key of ansible master node to all servers by password authentication
- name: Generate SSH key pairs of ansible master
  user:
    name: root
    generate_ssh_key: yes
  tags: add_public_key

- name: Add ansible master public key to nodes of cluster
  authorized_key: 
    user: root 
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
  tags:
    - add_public_key

# Configure trust access between remote nodes
- name: Fetch remote nodes public key files
  fetch:
    src: /root/.ssh/id_rsa.pub
    dest: /tmp/ansible_fetched
    #flat: yes
  tags:
    - add_public_key_between_nodes

- name: Merge remote nodes public keys
  shell: "grep -r ssh-rsa  /tmp/ansible_fetched/ | awk -F: '{print $2}' > /tmp/ansible_fetched/id_rsa.pub"
  vars:
    - ansible_become: false
    - ansible_connection: local
  tags:
    - add_public_key_between_nodes

- name: Add fetched public keys of every nodes to remote nodes
  authorized_key:
    user: root
    key: "{{ lookup('file', '/tmp/ansible_fetched/id_rsa.pub') }}"
  tags:
    - add_public_key_between_nodes
