---
# tasks file for hostname

#- name: Add hosts to /etc/hosts
#  lineinfile:
#    dest: "/etc/hosts"
#    line: "{{ hostvars[inventory_hostname]['ansible_eth0']['ipv4']['address'] }} {{ hostvars[inventory_hostname]['ansible_hostname'] }}"
#  tags:
#    - hosts

- name: Config hosts file
  template:
    src: "hosts.j2"
    dest: "/etc/hosts"
